#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import re
import importlib
import os


from subsync_packages import color
from subsync_packages import synctime
from subsync_packages import calibrate


try:
    if(len(sys.argv)==1):
        print("usage: subsync [--help] [--sync-time] [--calibrate]")
    elif (sys.argv[1] == '--h' or sys.argv[1] == '--help' or sys.argv[1] == '-h' or sys.argv[1] == '-help' ):
        print('--sync-time\tTo find haste/delay between video and subtitle in sec')
        print('--calibrate\tTo sync subtitles')
    
    elif (sys.argv[1] == '--v' or sys.argv[1] == '--version' or sys.argv[1] == '-v' or sys.argv[1] == '-version' ):
        print('Version - v0.0.1')

    elif sys.argv[1] == '--sync-time':
        color.prCyan("\nType : INT (Input in number only)\n")
        synctime.synctime()

    elif sys.argv[1] == '--calibrate':
        calibrate.calibrate()
    else:
        print("unknown option: "+str(sys.argv[1]))
        print("usage: subsync [--help] [--sync-time] [--calibrate]")
except Exception:
    color.prRed("\nError Occured\n\n")
    print("usage: subsync [--help] [--sync-time] [--calibrate]")
    color.prYellow("\nRefer documentation for further explination with examples\n")
    print("Documentation link : ",end="")
    color.prGreen("https://kushtej.github.io/subsync\n\n")

